export type Recipe = {
  title: string;
  goal: string;
  syntax: string;
  parts: { code: string; meaning: string }[];
  steps: { title: string; desc: string }[];
  prototype?: string;
  returns?: string;
};

export const productionRecipes: Record<number, Recipe> = {
  1: { title: "Écrire et lancer un programme C", goal: "Partir d'une page vide et obtenir un programme qui s'exécute.", syntax: `#include <stdio.h>\nint main(void) {\n    instruction;\n    return 0;\n}`, parts: [{code:'#include <stdio.h>',meaning:'importe les fonctions d’entrée/sortie'}, {code:'int main(void)',meaning:'fonction de départ du programme'}, {code:'instruction;',meaning:'action à exécuter'}, {code:'return 0;',meaning:'fin normale du programme'}], steps:[{title:'1. Créer le fichier',desc:'Crée un fichier .c, par exemple programme.c.'},{title:'2. Écrire la structure',desc:'Ajoute #include puis int main(void) { }.'},{title:'3. Ajouter l’action',desc:'Place tes instructions dans les accolades et termine chaque instruction par ;.'},{title:'4. Compiler',desc:'gcc programme.c -o programme'},{title:'5. Exécuter',desc:'./programme'}] },
  2: { title:"Déclarer et utiliser une variable", goal:"Construire une variable sans recopier un exemple au hasard.", syntax:`type nom;\ntype nom = valeur;`, parts:[{code:'type',meaning:'type de donnée : int, float, char, double…'},{code:'nom',meaning:'identifiant choisi selon les règles de nommage'},{code:'valeur',meaning:'donnée initiale compatible avec le type'}], steps:[{title:'1. Choisir le type',desc:'Détermine ce que la variable doit stocker.'},{title:'2. Choisir le nom',desc:'Commence par une lettre ou _, sans espace ni mot réservé.'},{title:'3. Déclarer',desc:'Écris type nom;.'},{title:'4. Initialiser',desc:'Si tu connais la valeur : type nom = valeur;.'},{title:'5. Modifier / lire',desc:'Affecte une nouvelle valeur avec = et utilise la variable dans une expression ou printf.'}], prototype:'printf(const char *format, ...);', returns:'printf retourne le nombre de caractères écrits (ou une valeur négative en cas d’erreur).' },
  3: { title:'Construire une expression avec les opérateurs', goal:'Choisir le bon opérateur et prévoir le résultat.', syntax:`gauche opérateur droite\n// exemple\nresultat = a + b;`, parts:[{code:'=',meaning:'affectation : place la valeur de droite dans la variable de gauche'},{code:'+ - * / %',meaning:'calculs arithmétiques'},{code:'== != < > <= >=',meaning:'comparaisons qui produisent 0 ou 1'},{code:'&& || !',meaning:'combiner ou inverser des conditions'}], steps:[{title:'1. Identifier le besoin',desc:'Calculer, comparer ou combiner une condition ?'},{title:'2. Choisir l’opérateur',desc:'Utilise l’opérateur correspondant à l’action.'},{title:'3. Vérifier les types',desc:'Attention notamment à la division entière et aux conversions.'},{title:'4. Stocker le résultat',desc:'Utilise une variable si le résultat doit être réutilisé.'}] },
  4: { title:'Construire une condition', goal:'Faire choisir au programme un chemin.', syntax:`if (condition) {\n    instructions;\n} else {\n    instructions;\n}`, parts:[{code:'if',meaning:'teste une condition'},{code:'condition',meaning:'expression évaluée à 0 (faux) ou non-zéro (vrai)'},{code:'else',meaning:'chemin exécuté si la condition est fausse'}], steps:[{title:'1. Formuler le test',desc:'Écris une expression vraie ou fausse.'},{title:'2. Écrire if',desc:'Place le test entre parenthèses.'},{title:'3. Écrire le bloc vrai',desc:'Mets les instructions entre accolades.'},{title:'4. Ajouter else si nécessaire',desc:'Décris le comportement lorsque le test est faux.'},{title:'5. Tester les deux cas',desc:'Vérifie au moins un cas vrai et un cas faux.'}] },
  5: { title:'Construire une boucle', goal:'Répéter une action avec une règle d’arrêt.', syntax:`for (initialisation; condition; mise_a_jour) {\n    instructions;\n}`, parts:[{code:'initialisation',meaning:'prépare le compteur / état'},{code:'condition',meaning:'tant qu’elle est vraie, la boucle continue'},{code:'mise_a_jour',meaning:'fait évoluer l’état pour atteindre l’arrêt'}], steps:[{title:'1. Définir ce qui se répète',desc:'Choisis les instructions à placer dans le bloc.'},{title:'2. Définir l’état',desc:'Exemple : int i = 0;.'},{title:'3. Définir l’arrêt',desc:'Exemple : i < 10.'},{title:'4. Faire progresser l’état',desc:'Exemple : i++.'},{title:'5. Vérifier l’arrêt',desc:'Assure-toi que la condition finira par devenir fausse.'}] },
  6: { title:'Créer et appeler une fonction', goal:'Transformer une action répétable en bloc réutilisable.', syntax:`type_retour nom(type param1, type param2) {\n    ...\n    return valeur;\n}`, parts:[{code:'type_retour',meaning:'type de la valeur renvoyée, ou void'},{code:'nom',meaning:'nom de la fonction'},{code:'paramètres',meaning:'données reçues par la fonction'},{code:'return',meaning:'renvoie une valeur au code appelant'}], steps:[{title:'1. Définir le besoin',desc:'Décide ce que la fonction doit faire.'},{title:'2. Choisir les paramètres',desc:'Liste les données dont elle a besoin.'},{title:'3. Choisir le retour',desc:'Utilise le type adapté ou void si rien n’est retourné.'},{title:'4. Écrire le corps',desc:'Ajoute les instructions et return si nécessaire.'},{title:'5. Appeler',desc:'nom(valeur1, valeur2);'}], prototype:'type_retour nom(type param1, type param2);', returns:'La fonction retourne la valeur prévue par son type de retour.' },
  7: { title:'Construire un tableau', goal:'Déclarer, remplir et parcourir plusieurs valeurs du même type.', syntax:`type tableau[taille];\ntype tableau[taille] = {v1, v2, v3};\ntableau[index]`, parts:[{code:'type',meaning:'type commun des éléments'},{code:'taille',meaning:'nombre maximal d’éléments déclaré'},{code:'index',meaning:'position, de 0 à taille-1'}], steps:[{title:'1. Choisir le type',desc:'Tous les éléments ont le même type.'},{title:'2. Donner la taille',desc:'Réserve le nombre d’éléments nécessaire.'},{title:'3. Initialiser si besoin',desc:'Utilise { valeur1, valeur2, ... }.'},{title:'4. Accéder',desc:'Utilise tableau[index]. Le premier élément est tableau[0].'},{title:'5. Parcourir',desc:'Utilise généralement une boucle avec un index.'}] },
  8: { title:'Construire et utiliser un pointeur', goal:'Faire pointer une variable vers une adresse mémoire.', syntax:`type *ptr;\nptr = &variable;\n*ptr`, parts:[{code:'type *ptr',meaning:'déclare un pointeur capable de recevoir une adresse d’un type donné'},{code:'&variable',meaning:'donne l’adresse mémoire de variable'},{code:'*ptr',meaning:'déréférence : accède à la valeur située à cette adresse'}], steps:[{title:'1. Avoir une variable',desc:'Exemple : int age = 20;.'},{title:'2. Déclarer le pointeur',desc:'Écris int *p; : p est un pointeur vers un int.'},{title:'3. Lui donner une adresse',desc:'Écris p = &age;.'},{title:'4. Lire la valeur',desc:'Écris *p pour atteindre la valeur de age.'},{title:'5. Modifier par adresse',desc:'Écris *p = 30; pour modifier age.'}], returns:'Un pointeur stocke une adresse ; *p permet d’accéder à la valeur pointée.' },
  9: { title:'Manipuler une chaîne de caractères', goal:'Créer, lire et modifier du texte en C.', syntax:`char texte[TAILLE];\nchar texte[] = "Bonjour";`, parts:[{code:'char',meaning:'chaque caractère est stocké dans un char'},{code:'[TAILLE]',meaning:'réserve une suite de caractères'},{code:'\\0',meaning:'caractère nul qui termine une chaîne C'}], steps:[{title:'1. Réserver l’espace',desc:'Prévois une case supplémentaire pour \\0.'},{title:'2. Initialiser',desc:'Utilise une chaîne entre guillemets.'},{title:'3. Lire',desc:'Choisis scanf, fgets ou une autre méthode selon le besoin.'},{title:'4. Manipuler',desc:'Utilise les fonctions de <string.h> avec des tailles maîtrisées.'},{title:'5. Vérifier la limite',desc:'Ne jamais écrire au-delà du tableau.'}] },
  10: { title:'Définir et utiliser une structure', goal:'Créer un modèle puis des objets avec plusieurs champs.', syntax:`struct Nom {\n    type champ1;\n    type champ2;\n};\nstruct Nom objet;`, parts:[{code:'struct Nom',meaning:'définit le modèle de données'},{code:'champ',meaning:'une donnée contenue dans la structure'},{code:'objet',meaning:'variable réelle créée à partir du modèle'},{code:'objet.champ',meaning:'accès à un champ'}], steps:[{title:'1. Définir le modèle',desc:'Liste les champs et leurs types.'},{title:'2. Terminer la définition',desc:'Ferme avec };.'},{title:'3. Déclarer un objet',desc:'Écris struct Nom objet;.'},{title:'4. Initialiser',desc:'Tu peux fournir les valeurs dans l’ordre des champs.'},{title:'5. Accéder',desc:'Utilise objet.champ.'}] },
  11: { title:'Allouer dynamiquement la mémoire', goal:'Réserver de la mémoire pendant l’exécution et la libérer correctement.', syntax:`type *p = malloc(nombre * sizeof *p);\n...\nfree(p);`, parts:[{code:'malloc',meaning:'réserve un bloc de mémoire'},{code:'sizeof *p',meaning:'calcule la taille du type pointé'},{code:'p',meaning:'reçoit l’adresse du bloc'},{code:'free(p)',meaning:'libère la mémoire réservée'}], steps:[{title:'1. Déterminer la quantité',desc:'Calcule le nombre d’éléments nécessaires.'},{title:'2. Déclarer le pointeur',desc:'Utilise le type des données à stocker.'},{title:'3. Allouer',desc:'malloc(n * sizeof *p).'},{title:'4. Vérifier',desc:'Teste p != NULL avant utilisation.'},{title:'5. Libérer',desc:'Appelle free(p) exactement lorsque le bloc n’est plus utile.'}], prototype:'void *malloc(size_t size);', returns:'Adresse du bloc alloué, ou NULL si l’allocation échoue.' },
  12: { title:'Ouvrir, lire/écrire et fermer un fichier', goal:'Manipuler un fichier sans oublier les étapes de sécurité.', syntax:`FILE *f = fopen("data.txt", "r");\nif (f != NULL) {\n    ...\n    fclose(f);\n}`, parts:[{code:'FILE *',meaning:'pointeur vers le flux fichier'},{code:'fopen',meaning:'ouvre le fichier selon un mode'},{code:'"r" / "w" / "a"',meaning:'lecture / écriture avec remplacement / ajout'},{code:'fclose',meaning:'ferme le flux et libère les ressources'}], steps:[{title:'1. Déclarer',desc:'FILE *f; — f recevra le flux ouvert.'},{title:'2. Ouvrir',desc:'f = fopen("data.txt", "r");.'},{title:'3. Vérifier',desc:'Teste f != NULL avant toute lecture/écriture.'},{title:'4. Utiliser',desc:'Choisis fgets/fscanf pour lire ou fprintf/fputs pour écrire.'},{title:'5. Fermer',desc:'fclose(f); dès que le fichier n’est plus utilisé.'}], prototype:'FILE *fopen(const char *filename, const char *mode);', returns:'Un FILE * utilisable si l’ouverture réussit, sinon NULL.' },
  13: { title:'Organiser un programme en modules', goal:'Séparer déclarations, implémentations et programme principal.', syntax:`// fichier .h\ntype fonction(...);\n\n// fichier .c\ntype fonction(...) { ... }\n\n// main.c\n#include "module.h"`, parts:[{code:'.h',meaning:'déclarations et prototypes visibles par les autres fichiers'},{code:'.c',meaning:'implémentation des fonctions'},{code:'#include "module.h"',meaning:'rend les déclarations du module disponibles'}], steps:[{title:'1. Déclarer',desc:'Place les prototypes dans le .h.'},{title:'2. Implémenter',desc:'Écris les fonctions dans le .c.'},{title:'3. Inclure',desc:'Inclue le .h là où les fonctions sont utilisées.'},{title:'4. Compiler ensemble',desc:'gcc main.c module.c -o programme'},{title:'5. Éviter les doublons',desc:'Utilise des gardes d’inclusion dans les headers.'}] },
  14: { title:'Construire une fonction récursive', goal:'Faire résoudre un problème par appels successifs jusqu’à un cas d’arrêt.', syntax:`type f(param) {\n    if (cas_arret) return resultat;\n    return f(param_modifie);\n}`, parts:[{code:'cas d’arrêt',meaning:'condition qui empêche les appels de continuer'},{code:'appel récursif',meaning:'la fonction s’appelle elle-même avec un problème plus petit'},{code:'param_modifie',meaning:'doit rapprocher l’appel du cas d’arrêt'}], steps:[{title:'1. Découper le problème',desc:'Trouve une version plus petite du même problème.'},{title:'2. Écrire le cas d’arrêt',desc:'C’est obligatoire pour éviter une récursion infinie.'},{title:'3. Écrire l’appel',desc:'Appelle la fonction avec un paramètre qui progresse.'},{title:'4. Retourner le résultat',desc:'Assemble le résultat de l’appel récursif.'},{title:'5. Tester',desc:'Teste d’abord le cas minimal puis quelques valeurs.'}] },
  15: { title:'Maîtriser les pointeurs avancés', goal:'Comprendre les pointeurs de pointeurs, tableaux de pointeurs et pointeurs de fonctions.', syntax:`type **pp;\ntype (*fonction)(parametres);`, parts:[{code:'**pp',meaning:'pointeur vers un pointeur : pp contient l’adresse d’un pointeur'},{code:'(*fonction)(...)',meaning:'déclare un pointeur vers une fonction compatible avec cette signature'}], steps:[{title:'1. Lire de l’intérieur',desc:'Identifie d’abord le type réellement manipulé.'},{title:'2. Compter les *',desc:'Chaque * ajoute un niveau d’indirection.'},{title:'3. Vérifier les types',desc:'L’adresse stockée doit correspondre au type attendu.'},{title:'4. Utiliser avec prudence',desc:'Déréférence seulement une adresse valide.'},{title:'5. Tester petit',desc:'Commence avec un exemple minimal avant une structure complexe.'}] },
  16: { title:'Déboguer et corriger un programme', goal:'Passer d’un bug constaté à une correction vérifiée.', syntax:`Observer → reproduire → localiser → corriger → tester`, parts:[{code:'compiler',meaning:'repère les erreurs de syntaxe et certains problèmes'},{code:'warning',meaning:'signal à prendre au sérieux, même si le build réussit'},{code:'debugger',meaning:'permet d’observer l’exécution étape par étape'}], steps:[{title:'1. Reproduire',desc:'Obtiens le bug avec un cas précis.'},{title:'2. Lire le message',desc:'Commence par la première erreur utile.'},{title:'3. Localiser',desc:'Regarde la ligne signalée et les lignes juste avant.'},{title:'4. Corriger une chose',desc:'Fais une modification ciblée.'},{title:'5. Recompiler et retester',desc:'Vérifie que le bug est réellement supprimé et qu’aucun nouveau problème n’est apparu.'}] }
};
